<a href="/users">List</a>
<hr>
<?php if (count($errors) > 0): ?>
    <?php foreach ($errors as $error): ?>
        <div><?= $error ?></div>
    <?php endforeach ?>
    <br>
<?php endif ?>
<form action="/users" method="post">
    <div>
        <label>First Name *</label>
        <br>
        <input type="text" name="user[first_name]" value="<?= isset($old) ? htmlspecialchars($old->getFirstName()) : '' ?>">
    </div>
    <br>
    <div>
        <label>Last Name *</label>
        <br>
        <input type="text" name="user[last_name]" value="<?= isset($old) ? htmlspecialchars($old->getLastName()) : '' ?>">
    </div>
    <br>
    <input type="submit" value="Create">
</form>
