<a class="btn btn-link float-end" href="/users">Back</a>

<div class="row mt-3">
    <div class="col-4">
        <?php if (count($errors) > 0): ?>
            <?php foreach ($errors as $error): ?>
                <div class="alert alert-danger mb-0"><?= $error ?></div>
            <?php endforeach ?>
            <br>
        <?php endif ?>

        <form action="/users/<?= $user->getId() ?>" method="post">
            <input type="hidden" name="_METHOD" value="PATCH">

            <div class="mb-3">
                <label class="form-label">First Name *</label>
                <input class="form-control" type="text" name="user[first_name]" value="<?= isset($old) ? htmlspecialchars($old->getFirstName()) : htmlspecialchars($user->getFirstName()) ?>">
            </div>

            <div class="mb-3">
                <label class="form-label">Last Name *</label>
                <input class="form-control" type="text" name="user[last_name]" value="<?= isset($old) ? htmlspecialchars($old->getLastName()) : htmlspecialchars($user->getLastName()) ?>">
            </div>

            <input class="btn btn-success" type="submit" value="Update">
        </form>
    </div>
</div>
