<a class="btn btn-primary my-3" href="/users/create">Create New</a>

<table class="table table-bordered">
    <thead class="table-light">
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <a href="/users/<?= $user->getId() ?>/edit"><?= htmlspecialchars($user->getId()) ?></a>
                </td>
                <td><?= htmlspecialchars($user->getFirstName()) ?></td>
                <td><?= htmlspecialchars($user->getLastName()) ?></td>
                <td class="text-center" width="10%">
                    <form action="/users/<?= $user->getId() ?>" method="post">
                        <input type="hidden" name="_METHOD" value="DELETE">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </td>
            <tr>
        <?php endforeach ?>
    </tbody>
</table>
