<a href="/users/create">Create New</a>
<hr>
<table width="100%">
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <a href="/users/<?= $user->getId() ?>/edit"><?= htmlspecialchars($user->getId()) ?></a>
                </td>
                <td><?= htmlspecialchars($user->getFirstName()) ?></td>
                <td><?= htmlspecialchars($user->getLastName()) ?></td>
                <td width="10%">
                    <form action="/users/<?= $user->getId() ?>" method="post">
                        <input type="hidden" name="_METHOD" value="DELETE">
                        <input type="submit" value="Delete">
                    </form>
                </td>
            <tr>
        <?php endforeach ?>
    </tbody>
</table>
