<a class="btn btn-link float-end" href="/posts">Back</a>

<div class="row mt-3">
    <div class="col-4">
        <?php if (count($errors) > 0): ?>
            <?php foreach ($errors as $error): ?>
                <div class="alert alert-danger mb-0"><?= $error ?></div>
            <?php endforeach ?>
            <br>
        <?php endif ?>

        <form action="/posts" method="post">
            <div class="mb-3">
                <label class="form-label">Author *</label>
                <select class="form-control" name="post[author_id]">
                    <option></option>
                    <?php foreach ($users as $user) : ?>
                        <option value="<?= $user->getId() ?>" <?= isset($old) && $user->getId() === $old->getAuthorId() ? 'selected' : '' ?>><?= htmlspecialchars($user->getFirstName() . ' ' . $user->getLastName()) ?></option>
                    <?php endforeach ?>
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label">Title *</label>
                <input class="form-control" type="text" name="post[title]" value="<?= isset($old) ? htmlspecialchars($old->getTitle()) : '' ?>">
            </div>

            <div class="mb-3">
                <label class="form-label">Content *</label>
                <textarea class="form-control" name="post[content]"><?= isset($old) ? htmlspecialchars($old->getContent()) : '' ?></textarea>
            </div>

            <input class="btn btn-success" type="submit" value="Create">
        </form>
    </div>
</div>
