<a class="btn btn-primary my-3" href="/posts/create">Create New</a>

<table class="table table-bordered">
    <thead class="table-light">
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Content</th>
            <th>Author</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($posts as $post) : ?>
            <tr>
                <td>
                    <a href="/posts/<?= $post->getId() ?>/edit"><?= htmlspecialchars($post->getId()) ?></a>
                </td>
                <td><?= htmlspecialchars($post->getTitle()) ?></td>
                <td><?= htmlspecialchars($post->getContent()) ?></td>
                <td><?= $post->getAuthorName() ?></td>
                <td class="text-center" width="10%">
                    <form action="/posts/<?= $post->getId() ?>" method="post">
                        <input type="hidden" name="_METHOD" value="DELETE">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </td>
            <tr>
        <?php endforeach ?>
    </tbody>
</table>
