<h1>Create Post</h1>
<form action="/posts" method="post">
    <div class="form-group">
        <label>Title *</label>
        <input type="text" name="title" class="form-control" required="required">
    </div>
    <div class="form-group">
        <label>Body</label>
        <textarea type="text" name="body" class="form-control"></textarea>
    </div>
    <input type="submit" class="btn btn-primary" value="Create">
</form>