<a href="/posts">List</a>
<hr>
<?php if (count($errors) > 0): ?>
    <?php foreach ($errors as $error): ?>
        <div><?= $error ?></div>
    <?php endforeach ?>
    <br>
<?php endif ?>
<form action="/posts" method="post">
    <div>
        <label>Title *</label>
        <br>
        <input type="text" name="post[title]" value="<?= $post ? htmlspecialchars($post->getTitle()) : '' ?>">
    </div>
    <br>
    <div>
        <label>Content *</label>
        <br>
        <textarea name="post[content]"><?= $post ? htmlspecialchars($post->getContent()) : '' ?></textarea>
    </div>
    <br>
    <input type="submit" value="Create">
</form>
